### ISSUE TITLE
Memory issue

### ISSUE THREAD

**Issue by PierrickPochelu** [MI2DataLab/survshap#19]
Hi,

First, congratulations for this project,

It seems the memory and time complexity is O(2 power n) with n the number of features in the dataset.
https://github.com/MI2DataLab/survshap/blob/67a5b49e1cd4549c8e457f63667edec3eb75fefb/survshap/predict_explanations/utils.py#L29 

What do you propose when n is large ? (e.g., 300). Do you plan to code approximation method (E.g. based on Monte Carlo sampling) ?

Regards,

**Comment by krzyzinskim** [comment]
I believe it relates to #21 (thank you for your interest and contributions!). Of course, it's a good idea to calculate approximation by limiting the number of coalitions taken into account when calculating Shapley values. 

However, it's better to choose coalitions wisely, based on their kernel weights, not totally randomly. Efficient implementation of Kernel SHAP which is based on such approach is available in the [kernelshap](https://modeloriented.github.io/kernelshap/index.html) R package (you can see details [here](https://modeloriented.github.io/kernelshap/reference/kernelshap.html)). This improved Kernel SHAP is used in the [survex](https://modeloriented.github.io/survex/index.html) R package which contains various methods of explaining survival models, including the SurvSHAP(t) method. 

I plan to work on a Python package in the near future and test various ideas how SurvSHAP(t) calculations can be accelerated. Currently, a wrapper is added to the KernelSHAP explainer from the `shap` Python library. So you can set `calculation_method='shap'` in both `ModelSurvSHAP` and `PredictSurvSHAP` and see if it speeds up the calculation in your case.

**Comment by PierrickPochelu** [comment]
The problem is solved by https://github.com/MI2DataLab/survshap/pull/21

Thank you for the merge
