### ISSUE TITLE
compatible with time-varying models?

### ISSUE THREAD

**Issue by ziyit** [MI2DataLab/survshap#2]
Hello,

I was looking into your development and was wondering if the survshap function can accommodate longitudinal model (panel), e.g., time-varying Cox (Lifelines), Dynamic DeepHit, and Recurrent Survival Machines with competing risks? Thanks!

**Comment by krzyzinskim** [comment]
Hello, 
This is not possible at the moment. Algorithms for estimating Shapley values can't take into account longitudinal data during calculations. However, this is an interesting point. Thanks!
