### ISSUE TITLE
Example code to plot the shap values

### ISSUE THREAD

**Issue by raheems** [MI2DataLab/survshap#27]
Could you please point to an example code/notebook to plot the shap values in Python?

I found R codes for the plots in the repository but wondering if python sample code are available.

Thanks

**Comment by krzyzinskim** [comment]
In the Python package readme, there is a minimal code example that shows also how to create plots - you can check it [here](https://github.com/MI2DataLab/survshap/tree/main/survshap_package#basic-usage).
