### ISSUE TITLE
nquiry Regarding Legend Addition in plot_mean_abs_shap_values() Function

### ISSUE THREAD

**Issue by ntnhu-ctump** [MI2DataLab/survshap#29]
Dear Dr. Krzyziński and the MI2 Data Lab,

I extend my gratitude to you for developing the 'SurvSHAP' tool, which has proven instrumental in effectively ranking and visualizing the integrability of time-to-event models.  I am very interested in this package and would like to apply it for my further experiments. I am writing to seek guidance on a specific aspect.

I would appreciate your assistance in understanding how to incorporate legends for each line within the plot_mean_abs_shap_values() function. I aim to label the names of each predictive feature, similar to the presentation in your publication (figure 11, left).

Thank you very much in advance.

Best regards,

Nhu, NT.

**Comment by krzyzinskim** [comment]
Hello, 
First, thank you for your interest! 
Unfortunately, the plots for the publication (including Fig. 11) were prepared manually in R. There's [code](https://github.com/MI2DataLab/survshap/blob/main/paper/other_codes/plots.R) for all of them and they are prepared based on `.csv` files with results of experiments (you can see saving results [here](https://github.com/MI2DataLab/survshap/tree/main/paper/experiments)). However, it's not automated process.

**Comment by ntnhu-ctump** [comment]
Thank you very much for your information.

Best!
