### ISSUE TITLE
SurvSHAP model freezes for new data

### ISSUE THREAD

**Issue by Addicted-to-coding** [MI2DataLab/survshap#4]
Hi,
I am trying to run SurvSHAP on my test dataset of shape 200x8 and the model ends up freezing without any error messages

1) I was able to reproduce the results of the paper by running https://github.com/MI2DataLab/survshap/blob/main/exp3.ipynb
2) My dataset is very similar to the dataset used in epx3. Using my dataset, I am able to generate the integrated brier scores of the rsf pipeline
3) However, when I try to use the SurvivalModelExplainer and ModelSurvShap to generate explanations, I get the following progress bar that does not run. I have tested this over the course of 10 hours and there is no progress, as well as no error message
![image](https://user-images.githubusercontent.com/28642161/203156596-ad57c842-b4ee-4489-b0af-f29e5117c64d.png)

4) As mentioned earlier, my dataset is similar to the default dataset used in exp3.ipynb, which runs just fine.
Can you please help out with this?

**Comment by hbaniecki** [comment]
Hi, thanks for reproducing our results!

I guess we are unable to debug such a freeze without a reproducible example (demo with code/data).

Closing and moving the discussion to #5
