### ISSUE TITLE
🆘  How to specify timestamps

### ISSUE THREAD

**Issue by maxnach92** [MI2DataLab/survshap#9]
Hello,

We're currently trying to estimate SHAP values from a random forest survival object (n=8000, predictors = 8) and we are getting tremendous running times. We were wondering whether we could reduce the number of timestamps (e.g. 2 years, 5 years and 10 years instead of a 100 equally-spaced times) - and hence reduce the running time. However, we're not sure how to pass it to the function (we tried with R and it failed). 

``` python
from survshap import SurvivalModelExplainer, ModelSurvSHAP
rsf_exp = SurvivalModelExplainer(rsf, X[1:300], y[1:300])

exp3_survshap_global_rsf = ModelSurvSHAP(random_state=42)
exp3_survshap_global_rsf.fit(rsf_exp)
```

Any help would be greatly appreciated, thank you for this amazing package.

**Comment by krzyzinskim** [comment]
Hi, sorry for the late reply. 

The answer is yes, it is possible to reduce the number of timestamps and provide your own vector. 
You can do it as follows:

```python
exp3_survshap_global_rsf = ModelSurvSHAP(random_state=42)
exp3_survshap_global_rsf.fit(rsf_exp, timestamps = [1, 2, 3])
```
